---
title: "Wish list for functional analysis package"
author: "Jon Brodziak and Matthew Supernaw"
date: "2025-12-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Wish list for functional analysis package

- Read in and process a simplex file with 3 proportions (2-D simplex with sum to 1 constraint)
  + Read in and process a simplex file with N proportions
- More general output structure to write flat file with rows
being simplex points with calculated outputs
- Function outputs for each point in the simplex
  + loglikelihood
  + continuity
  + stochasticity
  + stochasticity derivatives
  + other outputs already calculated 
- Other new output
  + divergence of the function gradient at a point
  + capacity to create replicates at one point for stochastic variables
  + capacity to choose output variables
  + create a log file
- Checks
  + Correlations calculated in one test run were outside 
  of the interval [-1,1]
  + Covariance calculation 


