# code-E.R
# Revised 19-May-2026

library(mgcv)
library(dplyr)

run_code_E <- function(data_name = "acc_long", out_file = "results-code-E.txt") {
  
  con <- file(out_file, open = "wt")
  sink_start <- sink.number(type = "output")
  sink(con, type = "output")

  on.exit({
    while (sink.number(type = "output") > sink_start) {
      sink(type = "output")
    }
    close(con)
  }, add = TRUE)

  tryCatch({
    cat("Code E: Generalized Additive Model (GAM) Analysis\n")
    cat("Output file:", out_file, "\n")
    cat("Run time:", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"), "\n\n")

    if (!exists(data_name, envir = parent.frame(), inherits = TRUE)) {
      stop("Required data object '", data_name, "' not found.")
    }
    acc_long <- get(data_name, envir = parent.frame(), inherits = TRUE)
	
	acc_long <- acc_long %>%
  mutate(
    method = factor(method),
    metric = factor(metric),
    design_block = factor(design_block),
    G = as.numeric(G),
    theta_true = as.numeric(theta_true),
    theta_CV = as.numeric(theta_CV),
    sigma = as.numeric(sigma),
    mean_nsamp = as.numeric(mean_nsamp),
    p1 = as.numeric(p1),
    p2 = as.numeric(p2),
    accuracy = as.numeric(accuracy)
  )


    # Global GAM: Spatial error surface by method
    cat("Fitting Global GAM with spatial splines s(p1, p2) by method...\n")
    fit_gam <- gam(
      log1p(accuracy) ~ metric * method +
        s(p1, p2, by = method, k = 30) +
        design_block + G + theta_true + theta_CV + sigma + mean_nsamp,
      data = acc_long,
      method = "REML"
    )

    cat("Global GAM Summary:\n")
    print(summary(fit_gam))
    cat("\nGAM ANOVA Table:\n")
    print(anova(fit_gam))
    cat("\n")
	
	# Technical Diagnostics
	# Check if k=30 is sufficient and inspect residual distributions
	graphics.off() # Clear previous plots if necessary
	gam.check(fit_gam)

	# Visualizing Method-Specific Surfaces (Base mgcv)
	# This loops through each method to show the p1/p2 surface
	methods_list <- levels(acc_long$method)
	par(mfrow = c(2, 3)) # Adjust layout based on number of methods
	for(m in methods_list) {
		vis.gam(fit_gam, view = c("p1", "p2"), 
          cond = list(method = m), 
          plot.type = "contour", 
          main = paste("Method:", m),
          color = "topo")
	}

	# Modern Interpretation via 'gratia'
if (!requireNamespace("gratia", quietly = TRUE)) {
  install.packages("gratia")
}
library(gratia)

# Check the exact smooth labels generated by mgcv
smooth_names <- gratia::smooths(fit_gam)

cat("\nSmooth terms in fit_gam:\n")
print(smooth_names)

# Visualize all method-specific s(p1,p2) smooths
# Use explicit data with the same variable classes used to fit the GAM.

plot_data <- acc_long %>%
  mutate(
    method = factor(method, levels = levels(acc_long$method)),
    metric = factor(metric, levels = levels(acc_long$metric)),
    design_block = factor(design_block, levels = levels(acc_long$design_block)),
    G = as.numeric(G),
    theta_true = as.numeric(theta_true),
    theta_CV = as.numeric(theta_CV),
    sigma = as.numeric(sigma),
    mean_nsamp = as.numeric(mean_nsamp),
    p1 = as.numeric(p1),
    p2 = as.numeric(p2),
    accuracy = as.numeric(accuracy)
  )

cat("\nDrawing method-specific smooth terms with gratia...\n")

p_smooth <- gratia::draw(
  fit_gam,
  data = plot_data,
  select = "s(p1,p2)",
  partial_match = TRUE
)

print(p_smooth)

# Comprehensive model appraisal
cat("\nRunning gratia model appraisal...\n")
p_appraise <- gratia::appraise(fit_gam)
print(p_appraise)

# Partial effects of categorical parametric terms only
# Avoid drawing all numeric parametric terms automatically because this
# is where type mismatches can occur in the generated prediction grid.

cat("\nDrawing categorical parametric effects with gratia...\n")

gg_tensor <- gratia::draw(
  fit_gam,
  data = plot_data,
  parametric = TRUE,
  terms = c("metric", "method", "design_block")
)

print(gg_tensor)

############################################################################################

# Difference GAM: Comparing Method V vs Method III
cat("Analyzing difference between Method 'v' and Method 'iii'...\n")

diff_v_iii <- acc_long %>%
  filter(method %in% c("v", "iii")) %>%
  group_by(
    example_id, design_block, G, theta_true, theta_CV, sigma,
    mean_nsamp, p1, p2, metric, method
  ) %>%
  summarise(
    accuracy = mean(accuracy, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  tidyr::pivot_wider(
    names_from = method,
    values_from = accuracy
  ) %>%
  filter(
    !is.na(v),
    !is.na(iii)
  ) %>%
  mutate(
    diff = v - iii
  )

diff_v_iii <- diff_v_iii %>%
  mutate(
    design_block = factor(design_block, levels = levels(acc_long$design_block)),
    metric = factor(metric, levels = levels(acc_long$metric)),
    G = as.numeric(G),
    theta_true = as.numeric(theta_true),
    theta_CV = as.numeric(theta_CV),
    sigma = as.numeric(sigma),
    mean_nsamp = as.numeric(mean_nsamp),
    p1 = as.numeric(p1),
    p2 = as.numeric(p2),
    diff = as.numeric(diff)
  )

fit_diff_gam <- gam(
  log1p(abs(diff)) ~ metric +
    s(p1, p2, by = metric, k = 30) +
    design_block + G + theta_true + theta_CV + sigma + mean_nsamp,
  data = diff_v_iii,
  method = "REML"
)

cat("Difference GAM Summary (Method v - iii):\n")
print(summary(fit_diff_gam))
cat("\n")

cat("Analysis completed successfully.\n")

invisible(list(fit_gam = fit_gam, fit_diff_gam = fit_diff_gam))

  }, error = function(e) {
    cat("ERROR\n-----\n", conditionMessage(e), "\n")
    stop(e)
  })
}

run_code_E()

